### PR TITLE
Update WalkCommand.java

### PR DESCRIPTION
**Pull request by Xyphos**
added "leeway" parameter to override Citizen's default pathDistanceMargin, which is 1 by default. This will allow scripters to determine their own pathDistanceMargin.

### CODE REVIEW

**Comment by mergu** [comment]
Missing docs.

**Comment by mergu** [comment]
Also missing the part where you actually store the value. Did you even test this?

**Comment by Xyphos** [comment]
Docs?

I can't test it because when I compile it without error and upload to my server, it won't load the custom plugin due to a missing class nms.v15_1 error and I'm not sure how to fix it, plus I can't ask for help without getting into a conflict with a certain person, but I have spent the better half of two days trying to trace my way through the code and solve the problem with the pathfinding quitting 1 block short of the destination, yes I know it's part of Citizens, but I also know that Denizens can add functionality to override the default behavior in the script, I'm seriously not trolling, I'm trying to help.

**Comment by mergu** [comment]
Denizen*

Yes, docs. The documentation for your addition.

Don't open untested pull requests - ask questions if you run into issues. I believe anyone can contribute to the project but they need to follow proper procedures, such as discussing the change beforehand and properly testing the changes. Otherwise, I'm not sure why you expect anything to get merged and pushed out broken.

**Comment by Xyphos** [comment]
okay then.

how do I solve the "class not found" **nms.v1_15** exception thrown at runtime on plugin load even if it compiles without error?
if I can get my branch to work, I'll gladly follow procedures for merge, testing and docs included.

**Comment by mcmonkey4eva** [comment]
- NEVER open an untested PR.
- Support is given on Discord @ https://discord.gg/Q6pZGSR ... if you're not on the Discord, you definitely should not be going near PRs.
- Missing docs as mentioned.
- Why should this exist in the walk command, as opposed to using the relevant path_distance_margin mechanism?
- The pathDistanceMargin doesn't do what you're wanting to do. The distanceMargin does that. They're different, despite the similar name. This, of course, is the `distance_margin` mechanism.

> how do I solve the "class not found" nms.v1_15 exception thrown at runtime on plugin load even if it compiles without error?

Depends on... what the error is? You'll have to post the actual error messages before I could actually make any sense out of it. When you do, please do so on the support Discord, not here. It's quite possibly you just didn't build the denizen-parent maven target, or copied the wrong final jar file.

> "I'm seriously not trolling, I'm trying to help."

Your previous PR was definitely trolling. This one looks like you're *trying* to be serious but merely inexperienced and foolish/brazen. If you want to be helpfully involved in Denizen, as opposed to trolling - rejoin the Discord, and try to act mature this time rather than fighting with everybody.

**Pull request closed without merging**
