### PR TITLE
Adds set_xyrange mechanism

### PR DESCRIPTION
**Pull request by j4c3**
Uses existing Citizens WanderWaypointProvider function setXYRange.

### CODE REVIEW

**Comment by tal5** [comment]
Is there any specific reason to have both of these in one mechanism? might make more sense to have `x_range` and `y_range` separately, but open for discussion ofc

**Comment by j4c3** [comment]
The existing Citizens method wants both, so we'd have to pull the exiting value for the other one, and I could only get it to give me the default value.

**Comment by tal5** [comment]
> The existing Citizens method wants both, so we'd have to pull the exiting value for the other one, and I could only get it to give me the default value.

[Citizens itself](https://github.com/CitizensDev/Citizens2/blob/e1a4f88126f5b38d1876adf27e2026de18844483/main/src/main/java/net/citizensnpcs/trait/waypoint/WanderWaypointProvider.java#L107-L111) seems to handle it that way, so I'd say splitting them up would make sense - what do you mean by `I could only get it to give me the default value`? how did you try reading it?

**Comment by j4c3** [comment]
"Integer xrange = wanderWaypointProvider.xrange;" would only return the default value, not current, and any other places it contained the values were private, I think. 

But, Fullwall has been making changes, and there are getters and setters for things that weren't there before.  Wandering is broken atm, but I will update this to utilize those new methods, and we can do x and y individually.

There are also methods to set worldguardRegion, pathfinding and delay values, now.  

But, should this be renamed to set_wanderxrange?

**Comment by tal5** [comment]
> "Integer xrange = wanderWaypointProvider.xrange;" would only return the default value, not current, and any other places it contained the values were private, I think.
> 
> But, Fullwall has been making changes, and there are getters and setters for things that weren't there before. Wandering is broken atm, but I will update this to utilize those new methods, and we can do x and y individually.
> 
> There are also methods to set worldguardRegion, pathfinding and delay values, now.
> 
> But, should this be renamed to set_wanderxrange?

Denizen doesn't use `set`/`get` prefixes for stuff generally, can be `wander_x_range`, or probably just `x_range`?
Should also add tags to read the x/y range, 2 tag & mech pairs.

**Comment by mcmonkey4eva** [comment]
Closing for now, can reopen if/when you revise it per the comments above

**Pull request closed without merging**
