### PR TITLE
Denizens or Sentry bug

### PR DESCRIPTION
**Pull request by Blamo27**
Sentry or Denizens bug ?
When I come into some area with NPC trait sentry
> http://timings.aikar.co/?url=14608817

### CODE REVIEW

**Comment by Blamo27** [comment]
TPS range : 2 - 5

**Comment by Talamar1** [comment]
What version of MC are you running?

**Comment by Blamo27** [comment]
My server is running CraftBukkit version git-Spigot-db6de12-d3e0b6f (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

**Comment by Talamar1** [comment]
Not according to your timings, it says 1.8.5 and the latest is 1.8.6.  You are also a few versions behind on Citizens (1292 vs 1298).

**Comment by Blamo27** [comment]
Yes but, when I download the latest sentry, It give me this version

**Comment by Blamo27** [comment]
http://ci.citizensnpcs.co/job/Sentry/28/artifact/target/sentry.jar
==> 1.8

**Comment by Talamar1** [comment]
That's weird, mcmonkey probably did something weird with the versions then.  Try updating your Cit and see if that helps.  Are you seeing any errors in the console?

**Comment by Blamo27** [comment]
No errors, I'll describe you the problem :
We have some areas on our server that contain many NPCs - sentries. Recently, two of these areas experience this problem : when we enter these places, as soon as the NPCs start looking for targets (that means, as soon as they are able to attack you if they see you : they are no longer iddle, passive), the TPS drops dramatically. We changed nothing in the affected areas, it just happened suddenly for no apparent reason. This problem does not occur in other areas, even if there are as many NPCs as in the affected places.

**Comment by Blamo27** [comment]
> Same problem with older Citizens versions.

**Comment by mcmonkey4eva** [comment]
Why the flip did you PR Denizen branches to report a Sentry bug?
Either way, Sentry is shite, use dSentry: http://mcmonkey.org/denizen/repo/entry/0

**Pull request closed without merging**
